name: Update cloud-native-sec-vuln repo
on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: Update cloud-native-sec-vuln
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VULN_LIST_DIR: "cloud-native-sec-vuln"
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check out cloud-native-sec-vuln repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ env.VULN_LIST_DIR }}
          path: ${{ env.VULN_LIST_DIR }}

      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Compile collect-cloud-native-sec-vuln
        run: go build -o collect .
      - if: always()
        name: Fetch vuln
        run: |
          CURRENT_DATE_TIME="update at $(date +'%Y-%m-%d %H:%M:%S')"
          ./scripts/update.sh "$CURRENT_DATE_TIME"