name: Update cloud-native-sec-vuln repo
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update cloud-native-sec-vuln
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY: "cloud-native-sec-vuln"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check out cloud-native-sec-vuln repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ env.REPOSITORY }}
          path: ${{ env.REPOSITORY }}
      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Compile
        run: go build -o collect .
      - if: always()
        name: Update
        run: ./scripts/update.sh
